### ISSUE TITLE
Word List

### ISSUE THREAD

**Issue by polycryptoblog** [satindergrewal/IguanaAtomicSwap#1]
We need  increase the size of the wordlist.  The current size of the wordlist doesn't lend enough entropy to thwart passphrase crackers.

**Comment by satindergrewal** [comment]
Saw your comments in SuperNET Slack's #btcd channel.

> polycryptoblog [12:05 PM]  
> looking at it,   we need to increase word list size, looks like only 200 or so words there

And here are my comments.

https://raw.githubusercontent.com/satindergrewal/IguanaAtomicSwap/master/assets/scripts/wordlist.js

> @polycryptoblog count all the words. these are all the words used in EasyDEX Wallet (edited)
> 2048 doesn’t look like 200
> or you talking 256bit instead 200 words ?
> It’s the same wordlist that Waves Lite client is using. and that’s a bit improved version of SuperNET Lite client’s word list.
> out of all those word list EasyDEX by default chooses 256bit passphrase, of around 24 words.
> Double the security of NXT wallet’s default passphrases
> Waves uses 160bit passphrase set, NXT uses 128bit passphrase set
> You can add even more words on top of what words are generated, but I think 256bit passphrase is more than enough to secure your accounts.
> Kinda double the standard of what industry is using.

**Comment by satindergrewal** [comment]
N/A
